openapi: 3.0.0
info:
  version: 1.0.0
  title: AccountService
servers:
  url: http://localhost:8080/api
paths:
  /accounts:
    get:
      summary: Get list of accounts
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/definitions/Pet'
        "404":
          description: Nothing found for your request
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'

    post:
      summary: Create new account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/Pet'
      responses:
        "201":
          description: Object craeted successfully
        "400":
          description: Bad request. The provided input does not comply to the contract.
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'
  /accounts/{accountId}:
    description: Get account details
    get:
      description: Retrieve account details
      parameters:
        - name: accountId
          in: path
          required: true
          description: The id of the account
          schema:
            type: string
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/definitions/Pet'
        "404":
          description: Nothing found for your request
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'
    delete:
      description: Delete account
      parameters:
        - name: accountId
          in: path
          required: true
          description: The id of the account
          schema:
            type: string
      responses:
        "204":
          description: Account deleted
        "404":
          description: Nothing found for your request
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/definitions/Error'

definitions:
  Pet:
    type: "object"
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  Pets:
    type: array
    items:
      $ref: '#/definitions/Pet'
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string